### ISSUE TITLE
Remove default values for most sensors

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pysensorproxy#1]
The config should give all information on how to connect sensors, instead of hiding this information in the code.

**Comment by oxzi** [comment]
> Closes issue #1

Should close the issue..

**Comment by oxzi** [comment]
This commit accidentally lost `Microphone`'s `rate` parameter, resulting in an incorrect state. @jonashoechst wanted to push a change soon, currently one has to hot-fix this :/
