### ISSUE TITLE
Communication raspberry TTGO

### ISSUE THREAD

**Issue by gisma** [Nature40/pysensorproxy#19]
As already discussed there is a major shortcome in the communication of the pi with the TTGO. As far as we have discussed now we will try the following

1. changing the protocol from UDP to TCP (27.02.)
2.  if (1) fails adding antennas we have to decide  (27.02.)  which antennas are suitable (any suggestions) 
3. if (2) also fails changing the the controller unit to something else (suggestions welcome)

**Comment by jonashoechst** [comment]
option 1 is addressed in 3c02bc4 and will be tested in the next hours

**Comment by jonashoechst** [comment]
The test in the forest showed promising results (25 meters tree), as only short stop was occurring.

This very stop always takes place at ~1.5 meters distance and could be seen in almost every test. My suggestion is, that a switch in the physical layer leads to some dropped / delayed packets.

**Comment by lampep** [comment]
now we have the best possible wifi connection between the raspberry and the TTGO. It is not perfekt but works. 
For further enhancement I want to open a new issue with other radio technologies in mind.
