### ISSUE TITLE
Each measurement creates a new file

### ISSUE THREAD

**Issue by gisma** [Nature40/pysensorproxy#20]
Is there a possibility to define the time interval that is stored in one file? It seems to be convinient for pictures and voice recordings to have single files  however for temperature/humidity and lumen this is pretty inconvenient. 
In addition some of these files contains no data other one data set or two.

**Comment by jonashoechst** [comment]
To have one single file is already intended behaviour, this clearly is a bug.

**Comment by eikeschott** [comment]
"bug" is fixed by disabling the rsync option - or increasing the time interval of rsync

**Comment by oxzi** [comment]
Each `LogSensor`'s filename will be changed after the `rsync` command was launched. This prevents overwriting of previously produced data. However, `rsync` should only be launched once each day and not every some minutes, as it is configured currently.
