### ISSUE TITLE
Microphone input pegel is extremly low

### ISSUE THREAD

**Issue by gisma** [Nature40/pysensorproxy#21]
The actual microphone recording settings (set to 100%) generates an extremely silent sound level. Tested with the low budget moicrophone it is not able to record a normal talk of two person 50 cm from the micro. Any suggestions?

**Comment by gisma** [comment]
We have checked the recordings with the image of  https://github.com/sarabsethi/rpi-eco-monitoring as described in  https://www.biorxiv.org/content/10.1101/236075v1
The recording is ways better and provides  at least almost  the quality that we expected. Is our configuration also driven by  `alsactl`?  If so we could easily try to integrate the configuration file of the above mentioed project.
BTW some fairly good ideas in this repo...

**Comment by jonashoechst** [comment]
As discussed in today evenings session, the microphone gain is set to the maximum. As done in the referenced project, the only option would be to boost the volume through alsa or other software. 

We decided to no boost the volume on the recording side, but rather on the evaluation side, as clipping can be avoided by this.
