### ISSUE TITLE
Cameras sometimes produce black images

### ISSUE THREAD

**Issue by eikeschott** [Nature40/pysensorproxy#25]
Almost all tested cameras produce black images although there is enough light to produce an image. Back  images are about half in size of normal images.

**Comment by jonashoechst** [comment]
Reduced size of the images is caused by the jpeg compression algorithm. The black images are most likely produced by a connection error between camera and raspberry pi.

Please debug, e.g. with `raspistill`, and reopen when this turns out to be a software problem.
