### ISSUE TITLE
Run LoggingHandler threaded

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pysensorproxy#39]
When logging messages, the Handler runs on the main thread and thus can cause the log to slow down execution; especially when submitting e.g. via influx.

**Comment by gisma** [comment]
Do you think that this is causing the connection errors?

**Comment by jonashoechst** [comment]
generalized by publishing influx threaded in general (f0bf3af510aaa8442279a4ffdf11c0249759d3a4)
