### ISSUE TITLE
Coninuation of "measurement" when energy supply is cut off

### ISSUE THREAD

**Issue by goergen95** [Nature40/pysensorproxy#4]
https://github.com/Nature40/pysensorproxy/blob/b5444308b89503c9719a57a561fa435af23089c7/sensorproxy/sensors/environment.py#L10

Currently, when the energy supply of the sensor is cut off the program does not throw an error message and the measurment seems to continue with the last recorded value. Could you please fix that?

**Comment by jonashoechst** [comment]
This seems to be a non-trivial error, caused by the sensor and/or the way we use it.

Possible options to fix:

- use 3.3V instead of 5V
- use a pullup resistor to connect the sensor

**Comment by oxzi** [comment]
We tried to reproduce this issue yesterday on the same setup. The machine ran into a timeout after round about 30 seconds and printed the correct error message. In the meantime the timestamp of the old measurements have not changed. Some of the reporting users said, they have not waited this long. This should not be an issue with the software.
