### ISSUE TITLE
Workaround travelspeeds

### ISSUE THREAD

**Issue by gisma** [Nature40/pysensorproxy#46]
https://github.com/Nature40/pysensorproxy/blob/51ed2a314d4a424245031621d551dbb5cbba2dce/sensorproxy/lift.py#L386

Here the lost connection time periods should be integrated. This will be easily up to 15 % difference. This will also enable a first software hack to stop the lift at the bottom and top position and to *ignore* hall sensor signals in between. The latter means that the hall sensor status has to be checked against the real position.

**Comment by jonashoechst** [comment]
Integrating the connection losses would be a nice way. However, we have no way of recognizing a connection loss here. The lift commands are sent via UDP, and thus we get no information on lost packets (TCP showed much worse results). 

Also, at the time of calibration we have no information about the bottom and top position, so ignoring the hall sensors in between is not possible. What we could do, is to ignore hall sensor inputs for the middle 80% of regular travels, so only when approaching top or bottom, we would read the values.

**Comment by gisma** [comment]
then we **have** to use other sensors...
