### ISSUE TITLE
WiFi Lift stallings and overall quality

### ISSUE THREAD

**Issue by jonashoechst** [Nature40/pysensorproxy#48]
The lift does not move at a good quality at the moment, multiple stalls happen (see also #43)

**Comment by jonashoechst** [comment]
# Disable Wi-Fi Frame Aggregation

One reason could by aggregation of packets on the Wi-Fi level, called A-MPDU / A-MSDU. 
 - [https://www.tamosoft.de/htmlhelp/commwifi/capturing_a-mpdu_and_a-msdu_pa.htm](https://www.tamosoft.de/htmlhelp/commwifi/capturing_a-mpdu_and_a-msdu_pa.htm)
 - options in wpa_supplicant: [https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf](https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf)
 - [https://dri.freedesktop.org/docs/drm/80211/mac80211-advanced.html#aggregation](https://dri.freedesktop.org/docs/drm/80211/mac80211-advanced.html#aggregation)

**Comment by jonashoechst** [comment]
# Dedicated Channel

Another improvement would be to use a dedicated orthogonal Wi-Fi channel for the lift communication. Channel 1 is used for Wi-Fi mesh, channel 6 would be available.

**Comment by jonashoechst** [comment]
# Fixed Wi-Fi PHY mode

Fix the coding, so Wi-Fi reconfiguration does not lead to delays. E.G. 802.11b: data rate is high enough, latency could improve.

**Comment by gisma** [comment]
How should we test it? The Platane lift is on duty so preferebly there? And how can we count automatically the connection drops?

**Comment by jonashoechst** [comment]
Since this issue becomes present when going out of the lab, the problem needs to be tested in a mostly realistic environment. The Platane is certainly a good place, but is not a 100% forest replacement. I suggest to use a 4 Stage test cycle:

1. Lab - mostly debugging, e.g. no QI charging, but ethernet connection for debugging
2. Artificial Tree - as the outdoor setup, but more accessible
3. Platane - outdoors, but not reaching the maximum height
4. Marburg Open Forest - real deployment

**Comment by Friessn** [comment]
I definitely see the added value from the Platane setup, but think it is accessible enough that we do not need the artificial tree. 
The modified Platane setup now reaches 11m (previously ~7m) and is permanently accessible by us or even our technical staff. In order to keep development cycles short I would skip the artifical tree setup. 

The lab setup on the other hand should imho mimic the real setup as close as possible and fior instance at least should have a Qi charging pad prepared if tests require it.

**Comment by gisma** [comment]
> * Lab - mostly debugging, e.g. no QI charging, but ethernet connection for debugging
> * Artificial Tree - as the outdoor setup, but more accessible
> * Platane - outdoors, but not reaching the maximum height
> * Marburg Open Forest - real deployment

I agree with @Friessn The debug levels will cost us 4 systems at minimum. In addition it is extremely time consuming to suüpport 4 setups that differ only in absolute height and more or less wind and rain. 

I think we agree that a WiFi conncetion **has** to reach out more than 30 meters on a line of  sight. So everything that works out at the plane tree will and has to work out in the forest - except the influence of the other running raspis...
An if @jonashoechst visit the plane tree you will find a lot of connection losses starting st 40 cm above ground.

**Comment by jonashoechst** [comment]
So the proposal of @Friessn is, to drop the Lab / Debug setting, which I am voting against, since I will not be able to develop code efficiently then.

IMO we do not loose 4 systems, 1) Lab setup is from our working group, and does exist already, 4) will act as a real setup, but will be the first to run the new version (that is already tested on 1-3). I think this will be the most systematic approach. 

> I think we agree that a WiFi conncetion **has** to reach out more than 30 meters on a line of sight. So everything that works out at the plane tree will and has to work out in the forest - except the influence of the other running raspis...

It surely has to reach out for this distance, however we all know that specs and reality differ. 

> An if @jonashoechst visit the plane tree you will find a lot of connection losses starting st 40 cm above ground.

Alright, I'll check next Monday.

**Comment by Friessn** [comment]
> 
> 
> So the proposal of @Friessn is, to drop the Lab / Debug setting, which I am voting against, since I will not be able to develop code efficiently then.

No, I only questioned the artificial tree (debug level 2), I definitvely am for a lab setup, preferably at your lab on the Lahnberge. 

So to be clear I see three debug levels: 
1 Lab setup - Code development, Minimum configuration (Location: maybe one at the Lahnberge and one in the Nat40-Lab)
2 Platane setup - Real world testing with increased accessibility (Location: Carolinenhaus)
3 MOF setup - Standard deployment (Location: Caldern)

My problem is not the material (you can use as many systems as you can build ;-) ) but the time it takes for development cycles to iterate.

**Comment by gisma** [comment]
I think the plane tree is fine for real testing and I promise if it this working there it will work in the forest too....
So run your office setup and run the plane tree. 
Otherwise you should calculate all the hours for senseless driving to the forest comparing and controlling all versions and so on. Not really time efficient. And Who is going to do it?
So please focus on the minimum setup that enables us to get rid of the burning problems.

**Comment by gisma** [comment]
IMO we need a scheme and priority list to check the compiled ideas. @jonashoechst would youplease make such a list and time table?

**Comment by Friessn** [comment]
The BLE solution should also be discussed here, but note my concerns concerning the development time stated in #45

**Comment by jonashoechst** [comment]
Three of the proposed improvements were implemented in a2c9e04 but do not show any better results, as the lift still stalls at the lab setup.

**Comment by jonashoechst** [comment]
# Skip Acknowledgements

Another idea would be, to skip the acknowledgements from the LiftSystem. Maybe this leads to collisions somehow...

**Comment by jonashoechst** [comment]
In the LiftSystem Firmware, two features were implemented: https://github.com/Nature40/Sensorboxes-Liftsystem/commit/2cab53e7a5ffa9ee6ed5ba7d38a691d25d53eeb3 

1. 802.11g Channel 11
2. ACK on change: only if speed changes, the value is sent back to the client.

**Comment by jonashoechst** [comment]
Commit 449508b15299c4b814d6fb39d523db9f0e6b204b changes pysensorproxy to set the timeout from the value defined in the config file.

With all the above changes and a 1 second timeout the system seems to be much more usable (tested at the platane). 

For now I declare this issue closed, however upcoming tests may show, that further improvements are required.
